version: 2
jobs:
  build:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest

    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            mkdir build
            cd build
            cmake ..
            make

      - run:
          name: Print the Current Time
          command: date
