version: 2
jobs:
  build_ubuntu:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest


    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake ..
            make

  build_centos:
    docker:
      - image: sgpearse/vapor3-centos7:latest

    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake ..
            make  

  printTime:
    docker:
      - image: sgpearse/vapor3-ubuntu:latest

    steps:
      - run:
        name: Print the Current Time
        command: date

workflows:
  version: 2
  build:
    jobs:
      - build_ubuntu
