version: 2
jobs:
  build:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest

    branches:
      only:
        - circleCI

    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR/build
            cmake ..
            make


      - run:
          name: Print the Current Time
          command: date
