version: 2
jobs:
  build:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - checkout
      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake ..
            make
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths: /VAPOR

    test:
      docker:
        - image: sgpearse/vapor3-ubuntu16:latest
      steps:
        - restore_cache: cache-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Running tests
            command: |
              cd /
              /VAPOR/build/bin/vaporversion > /version.txt
        - store_artifacts:
            path: /version.txt
            destination: vapor-version-info

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
