version: 2
jobs:
  build_ubuntu16:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest

    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake ..
            make


  build_ubuntu18:
    docker:
      - image: sgpearse/vapor3-ubuntu18:latest

    steps:
      - checkout

      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake ..
            make

  build_centos7:
    docker:
      - image: sgpearse/vapor3-centos7:latest

    steps:
      - checkout

      - run:
          name: cmake3 and make
          command: |
            cd /VAPOR
            git pull
            cd build
            cmake3 ..
            make


  build_osx: # runs not using `Workflows` must have a `build` job as entry point
    macos:  # indicate that we are using the macOS executor
      xcode: "11.1.0" # indicate our selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run:
          name: Install cmake
          command: brew install cmake3


  printTime:
    docker:
      - image: sgpearse/vapor3-ubuntu:latest

    steps:
      - run:
        name: Print the Current Time
        command: date

workflows:
  version: 2
  build:
    jobs:
      - build_ubuntu16
      - build_ubuntu18
      - build_centos7
      - build_osx
