version: 2.1

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build_osx_installer:
    macos:
      xcode: "12.4.0"
    steps:
      - run:
          name: Make VAPOR-Deps
          command: |
            sudo mkdir -p /usr/local/VAPOR-Deps
            sudo chmod -R 777 /usr/local/VAPOR-Deps
            sudo chown -R `whoami` /usr/local/VAPOR-Deps

      - checkout

      - run:
          name: Get dependencies 
          command: |
            export DEPS=/usr/local/VAPOR-Deps/2019-Aug-Darwin.tar.xz
            if [ ! -f $DEPS ]; then
                ~/project/.circleci/getOSXDeps.sh
            fi

      - run:
          name: make VAPOR
          command: |
            cp site_files/site.NCAR site.local
            mkdir build
            cd build
            git checkout $CIRCLE_BRANCH
            /usr/local/bin/cmake -DCPACK_BINARY_DRAGNDROP=ON -DCMAKE_BUILD_TYPE:String=Release -DDIST_INSTALLER:string=ON -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++ -DCMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -DCMAKE_CXX_FLAGS=-I/usr/local/opt/llvm/include -DCMAKE_EXE_LINKER_FLAGS=-L/usr/local/opt/llvm/lib -DUSE_OMP=ON -Wl,-rpath,/usr/local/opt/llvm/lib ..
            make
            make installer
            mkdir -p /tmp/installers
            mv *.dmg /tmp/installers
          no_output_timeout: 30m

      - store_artifacts:
          path: /tmp/installers

workflows:
  installers:
    jobs:
      - build_osx_installer
