version: 2
jobs:
  build:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - checkout
      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            git checkout $CIRCLE_BRANCH
            git pull
            cd build
            cmake ..
            make &> buildResults.txt
            ls ../test_apps
      - store_artifacts:
          path: /VAPOR/build/buildResults.txt
          destination: build-results
      - persist_to_workspace:
          root: /
          paths: VAPOR

  checkWarnings:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - attach_workspace: 
          at: /
      - run:
          name: Checking for warnings
          command: |
            cd /VAPOR
            git branch
            echo ''
            echo $CIRCLE_TAG
            echo ''
            echo $CIRCLE_BRANCH
            echo ''
            ls /VAPOR
            echo ''
            ls /VAPOR/test_apps
            echo ''
            ls /VAPOR/test_apps/circleTests
            echo ''
            /VAPOR/test_apps/circleTests/checkForWarnings.sh

  testVersion:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - attach_workspace: 
          at: /
      - run:
          name: Running tests
          command: |
            /VAPOR/build/bin/vaporversion > /version.txt
      - store_artifacts:
          path: /version.txt
          destination: vapor-version-info

workflows:
  version: 2
  build:
    jobs:
      - build
      - checkWarnings:
          requires:
            - build
      - testVersion:
          requires:
            - build
