version: 2.1

orbs:
  win: circleci/windows@2.2.0

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build_win10_installer:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            choco install visualstudio2019-workload-vctools -y
            choco install python -y
            choco install git -y
            choco install cmake -y
            choco install nsis -y
            python -m pip install gdown
            setx /M PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin"
            msbuild -version
            pwd
            ls
            python .circleci/downloadWin3rdParty.py
      - run:
          name: dos2unix
          command: |
            dos2unix /c/Users/circleci/project/share/shaders/*
            dos2unix /c/Users/circleci/project/share/shaders/main
            dos2unix /c/Users/circleci/project/share/shaders/includes
          shell: bash.exe
      - run:
          name: Build Vapor
          command: |
            Copy-Item site_files\* -Destination .
            mkdir build
            cd build
            git checkout $CIRCLE_BRANCH
            & 'C:\\Program Files\\CMake\\bin\\cmake.exe' -S C:\Users\circleci\project -B C:\Users\circleci\project\build -DDIST_INSTALLER:string=ON -DCMAKE_BUILD_TYPE:STRING=Release -G 'Visual Studio 16 2019' -A x64
            msbuild C:\Users\circleci\project\build\PACKAGE.vcxproj /p:Configuration=Release /p:Platform=x64
            mkdir -p C:\Users\circleci\project\tmp\installers
            Copy-Item C:\Users\circleci\project\build\*.exe -Destination C:\Users\circleci\project\tmp\installers
          no_output_timeout: 45m

      - store_artifacts:
          path: C:\Users\circleci\project\tmp\installers

workflows:
  build:
    jobs:
      - build_win10_installer
