version: 2
jobs:
  build:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - checkout
      - run:
          name: cmake and make
          command: |
            cd /VAPOR
            cd build
            cmake ..
            make &> buildResults.txt
      - store_artifacts:
          path: /VAPOR/build/buildResults.txt
          destination: build-results
      - save_cache:
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
          paths: /VAPOR
  checkWarnings:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - restore_cache: 
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Checking for warnings
          command: |
            ls /VAPOR
            echo ''
            ls /VAPOR/test_apps
            echo ''
            ls /VAPOR/test_apps/circleTests
            echo ''
            git branch
            echo ''
            /VAPOR/test_apps/circleTests/checkForWarnings.sh
  testVersion:
    docker:
      - image: sgpearse/vapor3-ubuntu16:latest
    steps:
      - restore_cache: 
          key: cache-{{ .Environment.CIRCLE_SHA1 }}
      - checkout
      - run:
          name: Running tests
          command: |
            /VAPOR/build/bin/vaporversion > /version.txt
      - store_artifacts:
          path: /version.txt
          destination: vapor-version-info

workflows:
  version: 2
  build:
    jobs:
      - build
      - checkWarnings:
          requires:
            - build
      - testVersion:
          requires:
            - build
